# Generated by Django 6.1.1 on 2026-09-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ambassador",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("university", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("status", models.CharField(default="Pending", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("dept", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.CharField(blank=True, max_length=100, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.TextField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("createdAt", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "ambassadors",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="WorkReport",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "ambassadorEmail",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "ambassadorName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=100)),
                (
                    "institution",
                    models.CharField(default="Campus Member", max_length=255),
                ),
                ("status", models.CharField(default="Pending", max_length=100)),
                ("createdAt", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "work_reports",
                "ordering": ["-createdAt"],
            },
        ),
    ]
