# Generated by Django 6.1.1 on 2026-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambassador",
            name="isAssessmentEligible",
            field=models.BooleanField(default=False),
        ),
    ]
