# Generated by Django 6.1.1 on 2026-09-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("createdAt", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "messages",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=100)),
                ("time", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("image", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("status", models.CharField(default="Upcoming", max_length=100)),
                ("regLink", models.CharField(blank=True, max_length=500, null=True)),
                ("createdAt", models.CharField(max_length=100)),
                ("updatedAt", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "events",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField(default=dict)),
                ("updatedAt", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "site_configs",
            },
        ),
    ]
