# Generated by Django 6.1.1 on 2026-09-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NfcOrder",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("customerName", models.CharField(max_length=255)),
                ("customerEmail", models.CharField(db_index=True, max_length=255)),
                ("customerPhone", models.CharField(max_length=100)),
                ("deliveryAddress", models.TextField()),
                ("district", models.CharField(default="Dhaka", max_length=100)),
                (
                    "cardVariantId",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cardVariantName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customNameOnCard",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customRoleOnCard",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "customOrgOnCard",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paymentMethod", models.CharField(default="bkash", max_length=100)),
                ("trxId", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ambassadorCode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("quantity", models.CharField(default="1", max_length=50)),
                ("unitPrice", models.CharField(default="0", max_length=50)),
                ("subtotal", models.CharField(default="0", max_length=50)),
                ("deliveryCharge", models.CharField(default="0", max_length=50)),
                ("discountAmount", models.CharField(default="0", max_length=50)),
                ("grandTotal", models.CharField(default="0", max_length=50)),
                ("status", models.CharField(default="Pending", max_length=100)),
                ("createdAt", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "nfc_orders",
                "ordering": ["-createdAt"],
            },
        ),
    ]
